[TSS]
TURRETS = [
  'GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX', # self
  'GAMGW7ZESFF2KVGL7EMBBIAXTFAOF3MNI2JBWSPLTGMAKOSVLHDNZMA2', # EverLife.AI
  'GCAQY54O7ABHNQDXNM3YLISXMX2B5M63GLB5SH6AIS66K7UXFYZ2GVPD', # Script3
]